import { defineConfig } from 'vitest/config'
import { resolve } from 'path'

export default defineConfig({
  resolve: {
    alias: {
      'bun:sqlite': resolve(__dirname, './test/__shims__/bun-sqlite.mjs'),
      'bun:test': resolve(__dirname, './test/__shims__/bun-test.mjs'),
    },
  },
  test: {
    include: [
      'test/constants/loop.test.ts',
      'test/deterministic-decomposer.test.ts',
      'test/hooks/audit-rotate-ordering.test.ts',
      'test/hooks/loop-section-audit-retry.test.ts',
      'test/hooks/loop-idle-gate.test.ts',
      'test/hooks/loop-event-gate.test.ts',
      'test/services/orphan-sweep.test.ts',
      'test/services/execution-restart.test.ts',
      'test/services/execution-in-flight-guard.test.ts',
      'test/services/execution.start-loop.test.ts',
      'test/services/parse-section-summary.test.ts',
      'test/utils/worktree-cleanup.test.ts',
      'test/utils/tui-client-workspaces.test.ts',
      'test/utils/workspace-status-registry.test.ts',
      'test/index/session-lookup.test.ts',
      'test/loop/termination.test.ts',
      'test/loop/state-mapper.test.ts',
      'test/loop/prompts.test.ts',
      'test/loop/transitions.test.ts',
      'test/loop/in-flight-guard.test.ts',
      'test/loop/runtime.test.ts',
      'test/loop/start.test.ts',
      'test/loop/cancel.test.ts',
      'test/plan-execution.test.ts',
      'test/loop-status-tool.test.ts',
      'test/workspace/forge-worktree.test.ts',
      'test/workspace/forge-adapter.test.ts',
      'test/workspace/forge-adapter-e2e.test.ts',
      'test/workspace/classify-stale.test.ts',
      'test/workspace/sweep-stale.test.ts',
      'test/sandbox-docker.test.ts',
      'test/sandbox-manager.test.ts',
      'test/sandbox/manager.test.ts',
      'test/sandbox/context.test.ts',
      'test/sandbox/reconcile.test.ts',
      'test/utils/sandbox-ready.test.ts',
      'test/loop-service.test.ts',
      'test/loop-service-notify.test.ts',
      'test/boot-sandbox-preserve.test.ts',
      'test/services/attach-loop.test.ts',
      'test/hooks/forge-session-attach.test.ts',
      'test/hooks/host-side-effects-unwarp.test.ts',
      'test/utils/tui-client-warp-flow.test.ts',
      'test/utils/tui-client-loop-inline-plan.test.ts',
      'test/services/execution-attach-cleanup.test.ts',
      'test/tui/execute-plan-panel-busy.test.ts',
      'test/hooks/plan-approval-dedupe.test.ts',
      'test/hooks/plan-approval-worktree-timing.test.ts',
      'test/services/select-initial-worktree-session.test.ts',
      'test/plan-approval.test.ts',
      'test/api-model-preferences.test.ts',
      'test/tui-execution-preferences.test.ts',
      'test/utils/tui-execution-context-cache.test.ts',
      'test/utils/tui-client-await-workspace-connected.test.ts',
      'test/utils/tui-client-select-session.test.ts',
      'test/loop-permission-ruleset.test.ts',
      'test/loop-runtime-audit-permissions.test.ts',
    ],
    globals: true,
  },
})
