import type { Language } from './types'

/** Identifier keywords to exclude from symbol searches */
export const IDENTIFIER_KEYWORDS = new Set([
  // ─── JS/TS keywords ───
  'const',
  'let',
  'var',
  'function',
  'class',
  'interface',
  'type',
  'export',
  'import',
  'from',
  'return',
  'async',
  'await',
  'new',
  'this',
  'super',
  'extends',
  'implements',
  'true',
  'false',
  'null',
  'undefined',
  'void',
  'string',
  'number',
  'boolean',
  'any',
  'never',
  'unknown',
  'for',
  'while',
  'if',
  'else',
  'switch',
  'case',
  'break',
  'continue',
  'try',
  'catch',
  'throw',
  'finally',
  'default',
  'static',
  'private',
  'public',
  'protected',
  'readonly',
  'abstract',
  'override',
  'typeof',
  'instanceof',
  'delete',
  'yield',
  'enum',
  'declare',
  'module',
  'namespace',
  'require',
  'of',
  'in',
  'as',
  'is',
  'keyof',
  'infer',
  'asserts',
  'satisfies',

  // ─── JS/TS globals (ECMAScript + Node built-in globals) ───
  'AbortController',
  'AbortSignal',
  'AggregateError',
  'Array',
  'ArrayBuffer',
  'Atomics',
  'BigInt',
  'BigInt64Array',
  'BigUint64Array',
  'Blob',
  'Boolean',
  'Buffer',
  'Crypto',
  'CryptoKey',
  'CustomEvent',
  'DOMException',
  'DataView',
  'Date',
  'Error',
  'ErrorEvent',
  'EvalError',
  'Event',
  'EventTarget',
  'File',
  'FinalizationRegistry',
  'Float32Array',
  'Float64Array',
  'FormData',
  'Function',
  'Headers',
  'Infinity',
  'Int16Array',
  'Int32Array',
  'Int8Array',
  'Intl',
  'Iterator',
  'JSON',
  'Map',
  'Math',
  'MessageChannel',
  'MessageEvent',
  'MessagePort',
  'NaN',
  'Navigator',
  'Number',
  'Object',
  'Performance',
  'Promise',
  'Proxy',
  'RangeError',
  'ReadableStream',
  'ReferenceError',
  'Reflect',
  'RegExp',
  'Request',
  'Response',
  'Set',
  'SharedArrayBuffer',
  'Storage',
  'String',
  'SubtleCrypto',
  'Symbol',
  'SyntaxError',
  'TextDecoder',
  'TextEncoder',
  'TransformStream',
  'TypeError',
  'URIError',
  'URL',
  'URLSearchParams',
  'Uint16Array',
  'Uint32Array',
  'Uint8Array',
  'Uint8ClampedArray',
  'WeakMap',
  'WeakRef',
  'WeakSet',
  'WebAssembly',
  'WebSocket',
  'WritableStream',
  'atob',
  'btoa',
  'clearImmediate',
  'clearInterval',
  'clearTimeout',
  'console',
  'crypto',
  'decodeURI',
  'decodeURIComponent',
  'encodeURI',
  'encodeURIComponent',
  'escape',
  'eval',
  'fetch',
  'global',
  'globalThis',
  'isFinite',
  'isNaN',
  'localStorage',
  'navigator',
  'parseFloat',
  'parseInt',
  'performance',
  'process',
  'queueMicrotask',
  'sessionStorage',
  'setImmediate',
  'setInterval',
  'setTimeout',
  'structuredClone',
  'unescape',
  // Node-specific globals
  '__dirname',
  '__filename',
  'exports',
  'Record',
  'Partial',
  'Required',
  'Readonly',
  'Pick',
  'Omit',
  'Exclude',
  'Extract',
  'NonNullable',
  'ReturnType',
  'Parameters',
  'ConstructorParameters',
  'InstanceType',
  'Awaited',
  'Uppercase',
  'Lowercase',
  'Capitalize',
  'Uncapitalize',

  // ─── JS/TS prototype & static methods (unambiguous names only) ───
  'charAt',
  'charCodeAt',
  'codePointAt',
  'concat',
  'endsWith',
  'includes',
  'indexOf',
  'lastIndexOf',
  'localeCompare',
  'normalize',
  'padEnd',
  'padStart',
  'repeat',
  'replace',
  'replaceAll',
  'slice',
  'split',
  'startsWith',
  'substring',
  'substr',
  'toLowerCase',
  'toLocaleLowerCase',
  'toUpperCase',
  'toLocaleUpperCase',
  'trim',
  'trimEnd',
  'trimStart',
  'trimLeft',
  'trimRight',
  'toString',
  'valueOf',
  'hasOwnProperty',
  'isPrototypeOf',
  'propertyIsEnumerable',
  'toLocaleString',
  'toFixed',
  'toPrecision',
  'toExponential',
  'toISOString',
  'toJSON',
  'toDateString',
  'toTimeString',
  // Array methods
  'copyWithin',
  'every',
  'fill',
  'filter',
  'findIndex',
  'findLast',
  'findLastIndex',
  'flatMap',
  'forEach',
  'isArray',
  'join',
  'length',
  'pop',
  'push',
  'reduce',
  'reduceRight',
  'reverse',
  'shift',
  'some',
  'sort',
  'splice',
  'unshift',
  'toReversed',
  'toSorted',
  'toSpliced',
  // Object/Reflect statics
  'assign',
  'defineProperty',
  'defineProperties',
  'freeze',
  'fromEntries',
  'getOwnPropertyDescriptor',
  'getOwnPropertyDescriptors',
  'getOwnPropertyNames',
  'getOwnPropertySymbols',
  'getPrototypeOf',
  'setPrototypeOf',
  'isExtensible',
  'isFrozen',
  'isSealed',
  'preventExtensions',
  // Map/Set methods
  'entries',
  'keys',
  'values',
  // JSON/Math statics
  'stringify',
  'abs',
  'ceil',
  'floor',
  'round',
  'trunc',
  'sqrt',
  'pow',
  'log',
  'log2',
  'log10',
  'random',
  'sign',
  // Promise
  'resolve',
  'reject',
  // Misc built-in methods
  'apply',
  'bind',
  'call',
  'constructor',
  'prototype',
  'existsSync',
  'readFileSync',
  'writeFileSync',
  'mkdirSync',

  // ─── Python keywords & builtins ───
  'def',
  'self',
  'None',
  'True',
  'False',
  'elif',
  'except',
  'raise',
  'pass',
  'with',
  'lambda',
  'nonlocal',
  'assert',
  'finally',
  'global',
  // Python builtins
  'str',
  'dict',
  'list',
  'tuple',
  'set',
  'frozenset',
  'int',
  'float',
  'bool',
  'bytes',
  'bytearray',
  'memoryview',
  'complex',
  'type',
  'object',
  'isinstance',
  'issubclass',
  'hasattr',
  'getattr',
  'setattr',
  'delattr',
  'callable',
  'classmethod',
  'staticmethod',
  'property',
  'super',
  'enumerate',
  'zip',
  'sorted',
  'reversed',
  'iter',
  'next',
  'range',
  'input',
  'open',
  'print',
  'repr',
  'format',
  'hash',
  'id',
  'dir',
  'vars',
  'globals',
  'locals',
  'exec',
  'compile',
  'breakpoint',
  '__init__',
  '__name__',
  '__main__',
  '__file__',
  '__all__',
  '__doc__',
  '__len__',
  '__getitem__',
  '__setitem__',
  '__delitem__',
  '__iter__',
  '__next__',
  '__enter__',
  '__exit__',
])

// Additional constants from repo-map-constants
export const INDEXABLE_EXTENSIONS: Record<string, Language> = {
  // TypeScript
  '.ts': 'typescript',
  '.tsx': 'typescript',
  '.mts': 'typescript',
  '.cts': 'typescript',
  // JavaScript
  '.js': 'javascript',
  '.jsx': 'javascript',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  // Python
  '.py': 'python',
  '.pyw': 'python',
  // Go
  '.go': 'go',
  // Rust
  '.rs': 'rust',
  // Java
  '.java': 'java',
  // C
  '.c': 'c',
  '.h': 'c',
  // C++
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cxx': 'cpp',
  '.hpp': 'cpp',
  '.hh': 'cpp',
  '.hxx': 'cpp',
  // C#
  '.cs': 'csharp',
  // Ruby
  '.rb': 'ruby',
  '.erb': 'ruby',
  // PHP
  '.php': 'php',
  // Swift
  '.swift': 'swift',
  // Kotlin
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  // Scala
  '.scala': 'scala',
  '.sc': 'scala',
  // Lua
  '.lua': 'lua',
  // Elixir
  '.ex': 'elixir',
  '.exs': 'elixir',
  // Dart
  '.dart': 'dart',
  // Zig
  '.zig': 'zig',
  // Shell
  '.sh': 'bash',
  '.bash': 'bash',
  '.zsh': 'bash',
  // OCaml
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  // Objective-C
  '.m': 'objc',
  // CSS
  '.css': 'css',
  '.scss': 'css',
  '.less': 'css',
  // HTML
  '.html': 'html',
  '.htm': 'html',
  // JSON
  '.json': 'json',
  '.jsonc': 'json',
  // TOML
  '.toml': 'toml',
  // YAML
  '.yaml': 'yaml',
  '.yml': 'yaml',
  // Dockerfile
  '.dockerfile': 'unknown',
  // Config/data files
  '.xml': 'unknown',
  '.md': 'unknown',
  '.sql': 'unknown',
  '.graphql': 'unknown',
  '.gql': 'unknown',
  '.proto': 'unknown',
  '.env': 'unknown',
  '.conf': 'unknown',
  '.ini': 'unknown',
  '.cfg': 'unknown',
}

/** Languages without meaningful AST symbols */
export const NON_CODE_LANGUAGES: ReadonlySet<Language> = new Set<Language>([
  'unknown',
  'css',
  'html',
  'json',
  'toml',
  'yaml',
  'dockerfile',
])

/** Languages where we can track cross-file imports via tree-sitter */
export const IMPORT_TRACKABLE_LANGUAGES: ReadonlySet<Language> = new Set<Language>([
  'typescript',
  'javascript',
  'python',
  'go',
  'rust',
  'java',
  'c',
  'cpp',
  'csharp',
  'ruby',
  'php',
  'swift',
  'kotlin',
  'scala',
  'dart',
  'ocaml',
  'objc',
  'solidity',
])

export const MAX_REFS_PER_FILE = 5000

export const PAGERANK_ITERATIONS = 20

export const PAGERANK_DAMPING = 0.85

export const DEFAULT_TOKEN_BUDGET = 2500

export const MIN_TOKEN_BUDGET = 1500

export const MAX_TOKEN_BUDGET = 4000

export const GIT_LOG_COMMITS = 300

export const MAX_COCHANGE_FILES_PER_COMMIT = 20

/** Batch size for graph scan operations - controls how many files are processed per RPC call */
export const GRAPH_SCAN_BATCH_SIZE = 500
