import { join, basename, isAbsolute } from 'path'
import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from 'fs'
import type { Logger } from '../types'

export const SHELL_SHIM_FILENAME = 'forge-shell'

/**
 * Environment variables consumed by the generated shim. Injected per shell-tool spawn via the
 * opencode `shell.env` plugin hook, so only agent shell commands are affected.
 */
export const SHIM_ENV_CONTAINER = 'FORGE_SANDBOX_CONTAINER'
export const SHIM_ENV_EXEC_USER = 'FORGE_SANDBOX_EXEC_USER'
export const SHIM_ENV_HOST_SHELL = 'FORGE_HOST_SHELL'

/**
 * Resolves the host shell baked into the shim's passthrough branch: `$SHELL` when it points at a
 * real shell (and not at a previously installed shim), otherwise a platform default.
 */
export function resolveHostShell(env: NodeJS.ProcessEnv = process.env): string {
  const candidate = env.SHELL
  if (
    candidate &&
    isAbsolute(candidate) &&
    basename(candidate) !== SHELL_SHIM_FILENAME &&
    existsSync(candidate)
  ) {
    return candidate
  }
  if (process.platform === 'darwin') return '/bin/zsh'
  if (existsSync('/bin/bash')) return '/bin/bash'
  return '/bin/sh'
}

export function buildShimScript(hostShell: string): string {
  return `#!/bin/sh
# Generated by opencode-forge; regenerated on plugin start. Do not edit.
#
# opencode's native bash tool is pointed at this script via the \`shell\` config
# key. Forge's shell.env hook sets ${SHIM_ENV_CONTAINER} for sessions that belong
# to an active sandbox loop, routing the command into the loop container. All
# other sessions fall through to the host shell unchanged.
#
# Fail-closed: when a container is expected, any docker failure surfaces as a
# non-zero exit — the command must never silently run on the host instead.
if [ -n "\${${SHIM_ENV_CONTAINER}:-}" ]; then
  if [ -n "\${${SHIM_ENV_EXEC_USER}:-}" ]; then
    exec docker exec --user "$${SHIM_ENV_EXEC_USER}" -w "$PWD" "$${SHIM_ENV_CONTAINER}" bash "$@"
  fi
  exec docker exec -w "$PWD" "$${SHIM_ENV_CONTAINER}" bash "$@"
fi
exec "\${${SHIM_ENV_HOST_SHELL}:-${hostShell}}" "$@"
`
}

/**
 * Writes the sandbox shell shim into the forge data directory (idempotent; rewrites only when
 * content drifts) and returns its absolute path. Returns null on failure so the caller can
 * degrade to worktree-only mode instead of leaving sandbox loops routed at the host shell.
 */
export function ensureShellShim(dataDir: string, logger: Logger): string | null {
  const path = join(dataDir, SHELL_SHIM_FILENAME)
  const content = buildShimScript(resolveHostShell())
  try {
    mkdirSync(dataDir, { recursive: true })
    let existing: string | undefined
    try {
      existing = readFileSync(path, 'utf-8')
    } catch {
      existing = undefined
    }
    if (existing !== content) {
      writeFileSync(path, content, { encoding: 'utf-8' })
    }
    chmodSync(path, 0o755)
    return path
  } catch (err) {
    logger.error(`Failed to install sandbox shell shim at ${path}`, err)
    return null
  }
}
